---
title:  "Resouces for Students"
---

## Really Good Teachers

A small list:

* My own teacher is <a href="https://ashtangayogastudio.com/" target="_blank">Andrew Eppler</a> in Oklahoma.
* <a href="https://www.ashtanga.net/" target="_blank">David Swenson</a> is one of the earliest American students of Aṣṭāṅga, and he still travels quite a bit to give Workshops.
* I have learned a lot over the years by visiting with <a href="https://www.ashtangayogacenter.com/" target="_blank">Tim Miller</a>, but he seems to be retired now.
* <a href="https://ashtangayogaclubdurham.com/" target="_blank">The Ashtanga Yoga Club of Durham</a> was founded by the late Suzanne Faulkner, one of the saints of the Aśṭāṅga community, along with her partner Nikos.  Now it continues under the leadership of Suzanne's yoga-sister <a href="https://joannadarlington.com/" target="_blank">Joanna Darlington</a>.  Both were students of <a href="https://davidgarrigues.com/" target="_blank">David Garrigue</a>, whose approach to the practice integrates elements of alignment-awareness.

## Primary Series Postures

Dr. Ronald Steiner collects a number of useful Aṣṭāṅga resources on his website, including "cheat-sheets" for the series <a href="https://www.ashtangayoga.info/ashtanga-yoga/cheat-sheets-pdf/" target="_blank">here</a>.^[Steiner's site is in German, with an option for English.  If you see a popup asking what you want to do about "cookies", it will probably be in German.  The button to accept cookies is the one on the left.]  You'll want the sheets for:

* Sun Salutation A & B
* Fundamental Positions with BNS Iyengar
* Primary Series with BNS Iyengar

## Primary Series Videos

* I teach a version of Primary Series of Aṣṭāṅga Yoga that was passed down by BNS Iyengar of Mysore, India, to my own teacher Andrew Eppler.  One of Andrew's students, Joey Paz, has produced a very accurate video of himself performing the BNS Iyengar Primary Series.  It can be purchased for a low price <a href="https://www.joeypazyoga.com/bns-primary-series" target="_blank">here</a>.
* In this <a href="https://www.youtube.com/watch?v=1Krp4W0TlAU" target="_blank">Youtube video</a> Laruga Glaser leads a student through a large fraction of the Primary Series, offering very sensible modifications to the postures.^[Laruga follows the more-commonly seen "Patabhi Jois" version of the Primary Series, so you'll notice a few small difference from what we do in class.]

## Mats and Rugs

If you practice Aṣṭāṅga consistently, you'll soon wear out a regular "sticky" mat within a year or so.  Most practitioners gravitate to one of the <a href="https://www.manduka.com/collections/yoga-mats" target="_blank">Manduka</a> mats:  being quite thick and tough, they save a lot of money in the long-run.^[I've had my Manduka for over twenty years and am only just now beginning to see signs of wear.]

Depending on the climate and the intensity of your practice, you may sweat enough to render your mat and the surface surrounding it rather slippery.  In that case you might want to put a "Mysore-style" cotton rug over your mat.  A popular vendor of rugs for Aṣṭāṅgis is <a href="https://ekaminhale.com/collections/yoga-rug"target="_blank">Ekam Inhale</a>.