---
title:  "Postures of the Primary Series"
draft: true
---

This article lists the postures of the Primary Series as taught by BNS Iyngar, along with a fairly standard variant of the encompassing vinyāsa,^[The vinyāsa qre based quite heavily on a video produced by Andrew Eppler, as part of the Yoga Methodology unit in his <a href="https://ashtangayogastudio.com/200hrtraining" target="_blank">Intensive Training</a> course.]  The postures are identified by their Sanskrit names, along with english translations.

It is important to bear in mind that, just as the postures themselves should be modified to individual bodies and needs, so the encompassing vinyāsa count should treated as aspirational only and should be subject to adjustment.  Even experienced persons who come to the practice with considerable bodily gifts find themselves adding breaths, especially as they move into or out of postures.

**Terminological Note**: The term *vinyāsa* is often used loosely to refer to the sequence of movments that form a transition from one seated posture to the next---lifitng up, jumping/stepping back to plank, up-dog, down-down, jump/step through to a sitting position to begin the next posture---but here it is used in its strict sense as one-half of a breath (either the inhale or the exhale) that is to be associated with a particular movement between postures as opposed to breaths taken while in the postures themselves.


## sūryanamakāra (Salutations to the Sun) Sequences

Andrew Eppler says that sūryanamaskāra are the meter and scale of the "song" that is the Primary Series.

### sūryanamakāra A Sequence

Repeat this sequence 4-5 times.  Only one posture of the sequence (adhomukhaśvānāsana)(is held.

Begin in __samasthitiḥ__.

1. inhale: raise arms and look up, to __ūrdhvavṛkṣāsana__ (Upward Tree Posture)
1. exhale: fold down to __uttanāsana A__ (Stretching Out Posture A)
1. inhale: straighten the spine and look forward but stay down (this is __uttanāsana B__, Stretching Out Posture A)
1. exhale: jump/step back to __caturaṅgadaṇḍāsana__ (Four-Limbed Stick Posture)
1. inhale: press up, bending back and looking up, to __ūrdhvamukhaśvānāsana__ (Upward-Face Dog Posture)
1. exhale: to __adhomukhaśvānāsana__ (Downward-Face Dog Posture).  *This posture is held for five complete breaths.*
1. inhale: jump/step forward to __uttanāsana B__
1. exhale: fold down to __uttanāsana A__
1. inhale: up to __ūrdhvavṛkṣāsana__
1. exhale: to __samasthitiḥ__

### sūryanamakāra B Sequence

Repeat this sequence 3-4 times as needed.  Again only one posture of the sequence (adhomukhaśvānāsana)(is held, and then only in its third occurence.

Begin in __samasthitiḥ__ from the final iteration of the sūryanamakāra A sequence.

1. inhale: raise arms and look up, to __ūrdhvavṛkṣāsana__ (Upward Tree Posture)
1. exhale: fold down to __uttanāsana A__ (Stretching Out Posture A)
1. inhale: straighten the spine and look forward but stay down (this is __uttanāsana B__, Stretching Out Posture A)
1. exhale: jump/step back to __caturaṅgadaṇḍāsana__ (Four-Limbed Stick Posture)
1. inhale: press up, bending back and looking up, to __ūrdhvamukhaśvānāsana__ (Upward-Face Dog Posture)
1. exhale: to __adhomukhaśvānāsana__ (Downward-Face Dog Posture).  *Do not hold this posture.*
1. inhale:  step right foot forward between hands, come up to __vīrabhadrāsana A__ (Auspicious Hero Posture A)
1. exhale:  step the right foot back, come down into __caturaṅgadaṇḍāsana__
1. inhale:  press up into __ūrdhvamukhaśvānāsana__
1. exhale:  to __adhomukhaśvānāsana__.  *Again, do not hold this posture.*
1. inhale:  step left foot forward between hands, come up to __vīrabhadrāsana A__ (Auspicious Hero Posture A)
1. exhale:  step the left foot back, come down into __caturaṅgadaṇḍāsana__
1. inhale:  press up into __ūrdhvamukhaśvānāsana__
1. exhale:  to __adhomukhaśvānāsana__.  *This time, hold the posture for five complete breaths.*
1. inhale: jump/step forward to __uttanāsana B__
1. exhale: fold down to __uttanāsana A__
1. inhale: up to __ūrdhvavṛkṣāsana__
1. exhale: to __samasthitiḥ__


## Standing Sequence

### pādāṅguṣṭhāsana (Thumb to Foot Posture)

Entering vinyāsa (4):

1. inhale: step left, hands to hips, look up
1. exhale: fold forward
1. inhale: straighten, look up
1. exhale: fold

(Here andrew stays down for the next posture. Joey Paz exits with four vinyāsa, ending in samasthitiḥ.)

### pādahastāsana (Hand [under] Foot Posture)

Entering vinyāsa (4):

1. inhale: look up, hands to hips
1. exhale: hands under feet
1. inhale: look up
1. exhale: fold

Exiting vinyāsa (4, ends in samasamasthitiḥ):

1. inhale: look up, hands to hips
1. exahle: fold
1. inhale: up
1. exhale: step back to samasamasthitiḥ

### trikoṇāsana (Triangle Posture) 

Entering vinyāsa (2):

1. inhale:  step to the left, feet a bit more than a leg's length distance apart, spread arms, "fix" the feet
2. exhale:  fold down to the right

Transition vinyāsa (2):

1. inhale:  rise up, fix feet the other way
2. exhale:  fold down to the left

Exiting vinyāsa (1):

* inhale:  rise up, fix feet the other way

### parivṛttatrikoṇāsana (Revolved Triangle Posture)

Entering vinyāsa (1):

* exhale:  fold and twist down and to the right

Transition vinyāsa (2):

1. inhale:  rise up, fix feet the other way
2. exhale:  fold and twist down and to the left

Exiting vinyāsa (2):

1. inhale:  rise up, feet back to neutral
2. exhale:  step back to samasamasthitiḥ


### parśvakoṇāsna (Side Angle Posture)

Entering vinyāsa (2):

1. inhale:  step to the left, feet quite a bit more than a leg's length distance apart, spread arms, "fix" the feet
2. exhale:  bend right knee over ankle, fold down to the right

Transition vinyāsa (2):

1. inhale:  rise up, fix feet the other way
2. exhale:  bend left knee over ankle, fold down to the left

Exiting vinyāsa (1):

* inhale:  rise up, fix feet the other way

### parivrttaparśvakoṇāsana (Revolved Side Angle Posture)

Entering vinyāsa (1):

* exhale:  bend right knee over ankle, fold and twist down and to the right

Transition vinyāsa (2):

1. inhale:  rise up, fix feet the other way
2. exhale:  bend left knee over angle, fold and twist down and to the left

Exiting vinyāsa (2):

1. inhale:  rise up, feet back to neutral
2. exhale:  step back to samasamasthitiḥ

### prasāritapādottānāsana (Stretching Out to Spread Feet Posture)

There are four variations:  A, B, C, D.

Entering vinyāsa for A (4):

1. inhale: step to the left, feet quite a bit more than a leg's length distance apart, spread arms
2. exhale:  hands on hips
3. inhale:  arch back, look up
4. exhale:  fold forwards, hands (and maybe head) on floor

Exiting vinyāsa from A (4):

1. inhale:  straighten the spine, look up but stay down
1. exhale:  hands on hips
1. inhale:  stand, arms out
1. exhale:  hands to hips

Entering vinyāsa for B (4):

* inhale stand, arms spread
* exhale hands to hips, elbows trending toward each other behind you
* inhale look up
* exhale fold down, head maybe on floor

Exiting vinyāsa from B (2):

1. inhale:  stand
1. exhale:  hands to hips

Entering vinyāsa for C (4):

1. inhale: spread arms
1. exhale: clasp ahnds behind back
1. inhale: arch back, look up
1. exhale:  fold down, head maybe on floor, hands on floor a distant possibility

Exiting vinyāsa from C (2):

1. inhale:  stand
1. exhale:  release clasp, hands to hips

Entering vinyāsa for D (4):

1. inhale: up arms wide
1. exhale: hands to hips
1. inhale: arch bak, look up
1. exhale: fold down, grab big toes, head maybe on floor

Exiting vinyāsa from D (4):

1. inhale:  straighten the spine, look up but stay down
1. exhale:  hands on hips
1. inhale:  stand, arms out
1. exhale:  step forward to samasamasthitiḥ

### parśvottānāsana (Stretching Out to the Side Posture)

Entering vinyāsa (4):

1. inhale: step left arms wide, less than a leg's width distance between feet
1. exhale: hands to reverse namaste
1. inhale: fix feet, turn torso to right, arch back and look up
1. exhale: fold into posture

Transition vinyāsa (4):

1. inhale: rise back up, arch back and look up
1. exhale: rotate to left, fixing feet other way
1. inhale: arch back, look up
1. exhale: fold

Exiting Vinyāsa (2):


1. inhale: rise back up, look up
1. exhale:  release hands, open arms, step forward to samasamasthitiḥ

## Primary Series Postures

### utthitahastapādāṅguṣṭhāsana (Big Toe of the Foot [grasped] with Risen Hand Posture)

to A:

* in take toe
* ex extend

to B:

* in out to right
* ex turn head left

to C:

* ex center
* in head up and grab
* ex head down

to D:

* in head back up
* ex hands on hips

2-2-3-2

same on the other side

### ardhabaddhapadmottānāsana (Stretching out in Half Bound Lotus Posture)

4 to enter
2 to exit (only 2!)

### utkaṭāsana (Fierce Posture)

**Note**:  In this posture the body resembles a jagged lightening-bolt; some people say this is why it is "fierce".

2 to enter but exhale is placeholder

exit is 2 (in up, ex to sama)

### vīrabhadrāsana (Auspicious Hero Posture)

**Note**:  "Vīrabhadra" is the name of an incarnation of Śiva.  Monier-Williams says:

>... in the Vāyu-Purāṇa he is said to have been created from Śiva's mouth in order to spoil the sacrifice of Dakṣa, and is described as having a thousand heads, a thousand eyes, a thousand feet, and wielding a thousand clubs; his appearance is fierce and terrific, he is clothed in a tiger's skin dripping with blood, and he bears a blazing bow and battle-axe; in another Purāṇa he is described as produced from a drop of Śiva's sweat.

5 to enter:

* in step arms wide
* ex turn lunge
* in up
* ex placehold

5 to transition:

* exhale 1 arms out to side
* inhale turn
* exhale turn and lunge 
* in up
* ex placehold

thne to B:  ex down

transition: in turn, ex settle in

exiting:

* ex down srep back
* in updog
* ex down
* inhale jump through

### daṇḍāsana (Stick Posture)



### paścimottānāsana (West Stretching out Posture)

ex, in ex then start 5 breaths 

three versions

3-2-2

### pūrvottānāsana (East Stretching out Posture)

4 to enter:

* in head up
* ex hands back
* in lift
* ex

standard jump-back and jump-through: 5 count

* in release
* ex back 
* in up-dog
* ex down-dog
* in jump through

### ardhabaddhapadmapaścimottānāsana (Half Bound Lotus West Stretching out Posture)

* in half-lotus
* ex reach around
* in look up
* ex fold forward

So that's actually a 9-count vinyāsa

But there are two inhales in a row!

exit is:

*in undo
* ex jump back
* in up
* ex down
* in jump
* ex lotus
* in look up
* ex fold

### tryaṅgamukhaikapādapaścimottānāsana (Three-Limbed Face to One Leg West Stretching out Posture)

* in release
* ex back
* in up
* ex down
* in through into posture and look up
* ex fold


### jānuśīrṣāsana (Head to Knee Posture)

* 8 to enter
* 10 to transition to next side

or think of it as 8 to get in, 2 to get out

### marīcyāsana (Marīci Posture)

This posture is dedicated to the sage <a href="https://en.wikipedia.org/wiki/Marichi" target="_blank">Marīci</a>.  There are four variations:  A, B, C and D.

* ex bend knee
* in forward
* ex complete the wrap around
* in look up
* ex fold forward

10 counts on both sides

B:  10 to get in, both sides

C:  5+3 to get in: ex knee up in twist exwarp around and grab

D:  5 + ex lotus, in knee up, ex twist, in arm up, ex wrap around and grab

### nāvāsana (Boat Posture)

5 to enter, begin count in exhale,

inhale up, exhale back into posture

### bhujapīḍāsana (Pressure on the Shoulders Posture)

in jump around, ex the start counting

on 5th ex, tuck down to B

### kūrmāsana (Tortoise Posture)

officially: in jump around, exhale flatten out


### suptakūrmāsana (Sleeping Tortoise Posture)

for the "less advanced" version, it's 2 to enter

### garbhapiṇḍāsana (Embryo in the Womb Posture)

ex into padma, in right hand ex left hand. take 5, then roll 9 times

### kukkuṭāsana (Rooster Posture)

you come up into it on an inhale

### baddhakoṇāsana (Bound Angle Posture)

no problem

### upaviṣṭakoṇāsana ("Entered Into" Angle Posture)

**Note**: *upaviṣṭa* can also mean "seated" but here it most likely refer to the way that the forward-folding torso "enters into" the angle formed by the legs.

* ex spread legs out
* in grab toes and look up
* ex fold

then in look up ex grab toes and all up


### suptakoṇāsana (Sleeping Angle Posture)

no jump-through transition, instead just
in get read ex roll back

in roll up, ex come down

and then do another 5 breaths!

### suptapadāṅguṣṭhāsana (Sleeping Thumb to Foot Posture)

There are four stages:  A, B, C, D.

* ex down
* in leg up
* ex draw shouler down

then B

then enter C

* on 5th exhale, flip hand over
* in bring leg around
* ex head within

another to count to enter D

Consider taking chakrāsana for the transition out.

### ubhayapādāṅguṣṭhāsana (Thumbs to Both Feet Posture)

the roll-back comes after!

### ūrdhvamukhapaścimottānāsana (Upward Face West Stretching out Posture)

roll up into this, no jump-through

### setubandhāsana (Bridge-Binding Posture)

10 to enter

Again consider chakrāsana for the transition out.

### ūrdhvadhanurāsana (Upward Bow Posture)

not more than 3 breaths between

do some kind of forward fold after

## Closing Sequence

### sālambhasarvāṅgāsana (Posture where All Limbs have Suppport)

in down, ex up

### hālāsana  (Plow Posture)

### karṇapīḍāsana (Pressure on the Ears Posture)

one ex in


### ūrdhvapadmāsana (Upward Lotus Posture)

4 to enter

### piṇḍāsana (Embryo Posture)

2 to enter


### matsyāsana (Fish Posture)

2 to enter

### uttānapādāsana (Legs Stretching out Posture)

2 to enter


### śīrṣāsana (Head[stand] Posture)

25 breaths, then come down holding for 5, maybe even do that three times

interesting he says in down ex up

### bālāsana (Child Posture)


### baddhapadmāsana (Bound Lotus Posture)

generally folks just sit down into this after previous

### padmāsana (Lotus Posture)

minimum 25 in this posture

prāṇāyāma, mudras encouraged here

### tolāsana (Lift Posture)

**Note**:  Monier-Williams cites *tolana* as "lifitng up" in the Rāmāyana.

### śāvāsana (Corpse Posture)